---
title: "Tidy Template"
author: "NearAndDistant"
date: "29/09/2021"
output: html_document
---

##  WED Du Bois Challenge 2022

#### Setup & Import
```{r}
library(tidyverse)

# create driectory for new project
dir.create(here::here("Week 7 : WED Du Bois Challenge 2022"))

# import data for project
slave_routes_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/slave_routes.csv")

world_cities <- maps::world.cities %>% select(name, country.etc, lat, long)

```

#### Clean & Wrangle
```{r}

# cleaning slave routes
slave_routes_cln <-
  slave_routes_raw %>%
  filter(!is.na(port_origin),
         port_origin != "???",
         !is.na(place_of_purchase),
         place_of_purchase != "???",
         !is.na(port_arrival),
         port_arrival != "???") %>%
  mutate(port_origin       = str_remove(port_origin      , ", port unspecified"),
         place_of_purchase = str_remove(place_of_purchase, ", port unspecified"),
         port_arrival      = str_remove(port_arrival     , ", port unspecified")) %>%
  mutate(port_origin       = if_else(port_origin       == "Africa.", "Africa", port_origin      ),
         place_of_purchase = if_else(place_of_purchase == "Africa.", "Africa", place_of_purchase),
         port_arrival      = if_else(port_arrival      == "Africa.", "Africa", port_arrival     ))

# port of origin count
ports <- 
slave_routes_cln %>%
  group_by(port_origin, place_of_purchase, port_arrival) %>%
  summarise(n_ships  = n(),
            n_slaves = sum(n_slaves_arrived, na.rm = TRUE)) %>%
  filter(n_slaves > 10000) %>%
  left_join(world_cities, by = c("port_origin" = "name"))

```

#### Joining
```{r}

port_country <- 
  ports %>% 
  mutate(country = if_else(port_origin %in% world_cities$country, port_origin, NA_character_)) %>%
  mutate(country = case_when(port_origin == "Great Britain"    ~ "UK",
                             port_origin == "Liverpool"        ~ "UK", 
                             port_origin == "London"           ~ "UK",
                             port_origin == "Bristol"          ~ "UK",
                             port_origin == "Lancaster"        ~ "UK",
                             port_origin == "Plymouth"         ~ "UK",
                             port_origin == "Newport"          ~ "USA",
                             port_origin == "Boston"           ~ "USA",
                             port_origin == "Rhode Island"     ~ "USA",
                             port_origin == "Bristol (RI)"     ~ "USA",
                             port_origin == "Havana"           ~ "Cuba",
                             port_origin == "Barcelona"        ~ "Spain",
                             port_origin == "San Lucar"        ~ "Spain",
                             port_origin == "Seville"          ~ "Spain",
                             port_origin == "Honfleur"         ~ "France",
                             port_origin == "Dunkerque"        ~ "France",
                             port_origin == "Middelburg"       ~ "Netherlands",
                             port_origin == "Zeeland"          ~ "Netherlands",
                             port_origin == "Hellevoetsluis"   ~ "Netherlands",
                             port_origin == "Rio de Janeiro"   ~ "Brazil",
                             port_origin == "Bahia"            ~ "Brazil",
                             port_origin == "Southeast Brazil" ~ "Brazil",
                             port_origin == "Pernambuco"       ~ "Brazil",
                             port_origin == "Africa"           ~ "Senegal", # largest African trading port
                             TRUE                            ~ country)) %>%
  left_join(world_cities, by = c("port_origin" = "city")) %>%
  mutate(country2 = if_else(country.x == country.y, country.x, NA_character_)) %>%
  mutate(country2 = if_else(is.na(country.y), country.x, country2)) %>%
  mutate(country2 = if_else(is.na(country2) & is.na(country.x), country.y, country2)) %>%
  filter(!is.na(country2))

```

#### Create Interrupted Goode Homolosine
tutorial, here: https://wilkelab.org/practicalgg/articles/goode.html

```{r}
library(cowplot)   # for theme_minimal_grid()
library(sf)        # for manipulation of simple features objects
library(rworldmap) # for getMap() [Do you want to install from sources the package which needs compilation? (Yes/no/cancel) no]

world_sf <- st_as_sf(getMap(resolution = "low"))

world_sf <- world_sf %>% janitor::clean_names() %>% select(sovereignt, geometry)

ggplot(world_sf) + 
  geom_sf(size = 0.5/.pt) +
  theme_minimal_grid()

# reproject
crs_goode <- "+proj=igh"

ggplot(world_sf) + 
  geom_sf(size = 0.5/.pt) +
  coord_sf(crs = crs_goode) +
  theme_minimal_grid()

# projection outline in long-lat coordinates
lats <- c(
  90:-90, # right side down
  -90:0, 0:-90, # third cut bottom
  -90:0, 0:-90, # second cut bottom
  -90:0, 0:-90, # first cut bottom
  -90:90, # left side up
  90:0, 0:90, # cut top
  90 # close
)
longs <- c(
  rep(180, 181), # right side down
  rep(c(80.01, 79.99), each = 91), # third cut bottom
  rep(c(-19.99, -20.01), each = 91), # second cut bottom
  rep(c(-99.99, -100.01), each = 91), # first cut bottom
  rep(-180, 181), # left side up
  rep(c(-40.01, -39.99), each = 91), # cut top
  180 # close
)

goode_outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc(crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# now we need to work in transformed coordinates, not in long-lat coordinates
goode_outline <- st_transform(goode_outline, crs = crs_goode)

# get the bounding box in transformed coordinates and expand by 10%
xlim <- st_bbox(goode_outline)[c("xmin", "xmax")]*1.1
ylim <- st_bbox(goode_outline)[c("ymin", "ymax")]*1.1

# turn into enclosing rectangle
goode_encl_rect <- 
  list(
    cbind(
      c(xlim[1], xlim[2], xlim[2], xlim[1], xlim[1]), 
      c(ylim[1], ylim[1], ylim[2], ylim[2], ylim[1])
    )
  ) %>%
  st_polygon() %>%
  st_sfc(crs = crs_goode)

# calculate the area outside the earth outline as the difference
# between the enclosing rectangle and the earth outline
goode_without <- st_difference(goode_encl_rect, goode_outline)

# run
ggplot(world_sf) + 
  geom_sf(size = 0.5/.pt) +
  geom_sf(data = goode_without, fill = "white", color = "NA") +
  coord_sf(crs = crs_goode) +
  theme_minimal_grid()

```

```{r}

port_origin_sf <-
world_sf %>%
  left_join(port_country, by = c("sovereignt" = "country2"))

```

```{r}

ggplot(port_origin_sf) + 
  geom_sf(aes(geometry = geometry), fill = "#e4b372", color = "#373737", size = 0.3/.pt, alpha = 0.85) +
  geom_curve(aes(x))
  geom_sf(data = goode_without, fill = "white", color = "NA") +
  geom_sf(data = goode_outline, fill = NA, color = "gray30", size = 0.5/.pt, linetype = "dashed") +
  coord_sf(crs = crs_goode, xlim = 0.95*xlim, ylim = 0.95*ylim, expand = FALSE) +
  theme_minimal_grid() +
  theme(panel.background = element_rect(fill = "white", color = "white", size = 1),
        panel.grid.major = element_blank())

```



#### Palette
```{r}
library(showtext); showtext_auto()
font_add_google("", "")
font_add_google("", "")

background <- 
palette    <- 

```

#### Plotting
```{r, fig.align="center", fig.width=6, fig.height=6, fig.cap="Figure: Here is a really important caption."}
ggplot2::theme_set(theme_mininal())



```

#### Panel
```{r}
library(cowplot)

# finalise panel with layered plotting or annotation
ggdraw() +
  draw_plot() +
  draw_text() +
  draw_text()

```

#### Saving
```{r}

ggsave(here::here(".png"), dpi = 360, height = 10, width = 15)

```

***

R markdown allows to easily format your text. You can add [links](www.r-graph-gallery.com), write in **bold** or *italic*.

Further formatting can be found [here](https://holtzy.github.io/Pimp-my-rmd/)

***