---
title: "Tidy Template"
author: "NearAndDistant"
date: "29/09/2021"
output: html_document
---

#### Setup & Import
```{r}
library(tidyverse)

# create driectory for new project
# dir.create(here::here())

# import data for project
black_prop_raw <- read_csv("https://raw.githubusercontent.com/ajstarks/dubois-data-portraits/master/challenge/2022/challenge04/data.csv")

black_prop <- 
  black_prop_raw %>% 
  janitor::clean_names() %>%
  rename(value = property_valuation) %>%
  mutate(color = case_when(year < 1875 ~ "pre",
                           year > 1898 ~ "post",
                           TRUE        ~ "none")) %>%
  mutate(plot  = "main",
         text  = NA_real_)

#sub sections of the main plot
black_prop_pre1874 <- black_prop %>% filter(color == "pre")
black_prop_po1899  <- black_prop %>% filter(color == "post")

# create a facet for y axis
y_axis <- tibble(year  = rep(1869,15),
                 value = c( 400000,  60000, 1000000, 
                           1400000, 160000, 2000000, 
                           2400000, 260000, 3000000, 
                           3400000, 360000, 4000000,
                           4300000, 450000, 4750000),
                 plot  = "y_axis",
                 color = "none",
                 text  = c("$", "$", "1,000,000",
                           "$", "$", "2,000,000",
                           "$", "$", "3,000,000",
                           "$", "$", "4,000,000",
                           "$", "$",   "DOLLAR"))
                 

```

#### Palette
```{r}
library(showtext); showtext_auto()
font_add_google("Rajdhani", "rajdhani")
font_add_google("Titillium Web", "web")

bg         <- "#e1d1c1" 

```

#### Plotting
```{r, fig.align="center", fig.width=6, fig.height=6, fig.cap="Figure: Here is a really important caption."}
library(cowplot)

#options(scipen=999)
x        <- 1000000
y_labels <- c("", 
              "", "", "", "$", "", "$", "", "", "", "1,000,000",
              "", "", "", "$", "", "$", "", "", "", "2,000,000",
              "", "", "", "$", "", "$", "", "", "", "3,000,000",
              "", "", "", "$", "", "$", "", "", "", "4,000,000",
              "", "",     "$", "", "$", "", "",     "DOLLAR")


black_property <-
black_prop %>%
  ggplot(aes(x = year, y = value)) +
  geom_line(size = 4.5, color = "#312e2c", alpha = 1) +
  geom_line(data = black_prop_pre1874, color = "#dccbba", size = 3, show.legend = FALSE) +
  geom_line(data = black_prop_po1899,  color = "#dccbba", size = 3, show.legend = FALSE) +
  # annotate
    # ku-klux klan
  ggtext::geom_richtext(aes(label = "KU-KLUXISM.",   x = 1872, y = 650000), 
                        family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA, label.padding = unit(0.1, "lines"), angle = 90) +
    # political unrest
  geom_label(aes(label = "POLITICAL", x = 1876, y = 2380000), family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA) +
  geom_label(aes(label = "UNREST.",   x = 1877.5, y = 2290000), family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA) +
    # new industrialism
  geom_label(aes(label = "RISE OF",        x = 1880, y = 4200000), hjust = 0, family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA) +
  geom_label(aes(label = "THE NEW",        x = 1882, y = 4100000), hjust = 0, family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA) +
  geom_label(aes(label = "INDUSTRIALISM.", x = 1884, y = 4000000), hjust = 0, family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA) +
    # lynching
  ggtext::geom_richtext(aes(label = "LYNCHING.",   x = 1892.5, y = 1550000), 
                        family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA, label.padding = unit(0.1, "lines")) +
    # financial panic
  ggtext::geom_richtext(aes(label = "FINANCIAL PANIC.",   x = 1894, y = 300000), 
                        hjust = 0, family = "rajdhani", size = 8, color = "#957469", fill = bg, label.size = NA, label.padding = unit(0.1, "lines"), angle = 90) +
    # new industrialism
  geom_label(aes(label = "DISFRANCHISMENT", x = 1896.5, y = 2480000), hjust = 0.5, family = "rajdhani", size = 6.5, color = "#957469", fill = bg, label.size = NA) +
  geom_label(aes(label = "AND",             x = 1896.5, y = 2400000), hjust = 0.5, family = "rajdhani", size = 6.5, color = "#957469", fill = bg, label.size = NA) +
  geom_label(aes(label = "PROSCRIPTIVE",    x = 1896.5, y = 2320000), hjust = 0.5, family = "rajdhani", size = 6.5, color = "#957469", fill = bg, label.size = NA) +
  geom_label(aes(label = "LAWS.",           x = 1896.5, y = 2240000), hjust = 0.5, family = "rajdhani", size = 6.5, color = "#957469", fill = bg, label.size = NA) +
  # ???
  geom_text(aes(label = "?", x = 1899.5,  y = 4320000), hjust = 0.5, family = "rajdhani", size = 4, color = "#35251f") +
  geom_text(aes(label = "?", x = 1873.1,  y = 1195000), hjust = 0.5, family = "rajdhani", size = 3, color = "#2b1815") +
  geom_text(aes(label = "?", x = 1870.25, y =  420000), hjust = 0.5, family = "rajdhani", size = 4, color = "#2b1815") +
  geom_text(aes(label = "?", x = 1870.7,  y =  650000), hjust = 0.5, family = "rajdhani", size = 4, color = "#2b1815") +
  geom_text(aes(label = "?", x = 1871.9,  y = 1060000), hjust = 0.5, family = "rajdhani", size = 4, color = "#2b1815") +
  scale_x_continuous(limits = c(1870, 1900),
                     expand = c(0,0),
                     breaks = seq(1870,1900,5),
                     minor_breaks = seq(1870,1900,1),
                     labels = seq(1870,1900,5)) + 
  scale_y_continuous(limits = c(0, x*4.85),
                     expand = c(0,0),
                     breaks = seq(0, x*4.8, x/10),
                     minor_breaks = seq(0,x*4.8, x/10),
                     labels = y_labels) +
  coord_cartesian(clip = "off") +
  labs(color = NULL,
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(panel.grid  = element_line(color = "#cda99f"),
        axis.text.x  = element_text(family = "rajdhani", size = 17),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(family = "rajdhani", size = 19, hjust = 0.2, margin = margin(r = -2.75, unit = "cm")),
        axis.ticks.y = element_line(color = "#cda99f"),
        axis.ticks.length.y = unit(6.5, units = "cm"),
        panel.border = element_rect(color = "#b0a08f", fill = NA, size = 0.8),
        plot.margin = margin(4,2,2.5,3, unit = "cm")) 

# cowplot
plot_black <- 
ggdraw(black_property) +
  draw_text("VALUATION  OF TOWN   AND   CITY   PROPERTY   OWNED", color = "#483c31", 
            x = 0.5, y = 0.97, family = "web", size = 28, fontface = "bold") +
  draw_text("BY   GEORGIA   NEGROES .",color = "#483c31",
            x = 0.5, y = 0.95, family = "web", size = 28, fontface = "bold") +
  annotate("rect", xmin = 0.07, xmax = 0.15, ymin = 0.0595, ymax = 0.92, color = "#b0a08f", fill = NA, size = 0.8) +
  # hide extra ticks
  annotate("rect", xmin = 0.15, xmax = 0.231, ymin = 0.0595, ymax = 0.23, color = bg, fill = bg, size = 0) +
  annotate("rect", xmin = 0.15, xmax = 0.231, ymin = 0.24,   ymax = 0.41, color = bg, fill = bg, size = 0) +
  annotate("rect", xmin = 0.15, xmax = 0.231, ymin = 0.42,   ymax = 0.59, color = bg, fill = bg, size = 0) +
  annotate("rect", xmin = 0.15, xmax = 0.231, ymin = 0.60,   ymax = 0.77, color = bg, fill = bg, size = 0) +
  annotate("rect", xmin = 0.15, xmax = 0.231, ymin = 0.78,   ymax = 0.94, color = bg, fill = bg, size = 0) +
  draw_text("[Data: Du Bois\nGraphic: @NearAndDistant]", x = 0.82, y = 0.02, hjust = 0, family = "rajdhani", size = 14, color = "#6e5b4d")

# saving
ggsave(plot = plot_black, here::here("Week 7 : WED Du Bois Challenge 2022/black_property.jpeg"), 
       dpi = 360, height = 20, width = 16, bg = bg)

```

```{r}
# side by side

ggdraw() +
  draw_image(here::here("Week 7 : WED Du Bois Challenge 2022/black_property.jpeg"),    x = -0.252) +
  draw_image(here::here("Week 7 : WED Du Bois Challenge 2022/original-plate-21.jpg"), x =  0.247)

```

***

R markdown allows to easily format your text. You can add [links](www.r-graph-gallery.com), write in **bold** or *italic*.

Further formatting can be found [here](https://holtzy.github.io/Pimp-my-rmd/)

***