---
title: "Tidy Template"
author: "NearAndDistant"
date: "29/09/2021"
output: html_document
---

##  Chocolate Ratings

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Setup & Import
```{r}
library(tidyverse)

# import data for project
chocolate_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv')

```

#### Analysis
```{r}

chocolate_avg <-
  chocolate_raw %>%
  group_by(country_of_bean_origin, review_date) %>%
  summarise(avg_rating = mean(rating))

```

```{r}

chocolate_table <-
chocolate_raw %>%
  count(country_of_bean_origin, review_date) %>%
  arrange(desc(n)) %>%
  filter(n >= 6)

```

#### Palette
```{r}
library(showtext); showtext_auto()
font_add_google("Comforter", "comfort")
font_add_google("", "")

background <- 
palette    <- 

```

```{r}

#plot_chocolate_bar <-
chocolate_avg %>%
filter(country_of_bean_origin %in% chocolate_table$country_of_bean_origin) %>%
  ggplot(aes(review_date, country_of_bean_origin)) + 
  geom_tile(aes(fill = avg_rating), colour = "white") + 
  scale_y_discrete(limits = rev) +
  nord::scale_fill_nord(palette = "halifax_harbor", na.value = "white", discrete = FALSE) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  labs(fill = "Chocolate Rating (Average)",
       x    = "Year of Review") +
  coord_equal() +
  theme_minimal() +
  theme(legend.position = "bottom", legend.key.width = unit(1, "cm"),
        legend.direction = "horizontal",
        axis.title.y = element_blank(),
        panel.grid = element_blank(),
        plot.margin = margin(4,1,2,1, unit = "cm"))

```

#### Panel
```{r}
library(cowplot)

# finalise panel with layered plotting or annotation
#final_choco <-
ggdraw(xlim = c(0.4,0.6)) +
  draw_plot(plot_chocolate_bar) +
  draw_text("Cocoa Beans", family = "comfort", size = 28,
            x = 0.5, y = 0.8)

```

#### Saving
```{r}

ggsave(here::here("final_plot.png"), dpi = 360, height = 10, width = 15, bg = "white")

```

***

R markdown allows to easily format your text. You can add [links](www.r-graph-gallery.com), write in **bold** or *italic*.

Further formatting can be found [here](https://holtzy.github.io/Pimp-my-rmd/)

***
