---
title: "Tidy Template"
author: "NearAndDistant"
date: "29/09/2021"
output: html_document
---

##  Chocolate Map

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Setup & Import
```{r}
library(tidyverse)

# import data for project
chocolate_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv')

```

#### Analysis
```{r}

chocolate_table <-
chocolate_raw %>%
  group_by(country_of_bean_origin) %>%
  summarise(n          = n(),
            avg_rating = mean(rating)) %>%
  arrange(desc(n)) %>%
  rename(name = "country_of_bean_origin")
  
```

#### Map

map projections: https://rstudio-pubs-static.s3.amazonaws.com/122915_0eeb3eb6bbfa4e8ca1838b633b8dc48f.html

```{r}
library(rgeos)
library(rworldmap)
library(sp)

vdg_coord <- CRS("+proj=vandg +lon_0=0 +x_0=0 +y_0=0 +R_A +a=6371000 +b=6371000 +units=m +no_defs")

# get world map
wmap <- getMap(resolution="high")
# get centroids
centroids <- gCentroid(wmap, byid=TRUE)
# get a data.frame with centroids
df <- as.data.frame(centroids) %>% rownames_to_column(var = "name") %>% 
      sf_transform_xy(source_crs = 4326, target_crs = vdg_coord)

library(rnaturalearth)
library(ggalt)
library(sf)

world <- ne_countries(returnclass = "sf", scale = "medium")

cao_world <- 
  world %>% 
  left_join(chocolate_table) %>% 
  left_join(df) %>%
  mutate(fill = if_else(is.na(avg_rating), "#d6cdbc", "#c48d82")) %>%
  mutate(avg_rating_cat = case_when(avg_rating >= 2.5  & avg_rating < 2.75   ~ "2.50 - 3.00",
                                    avg_rating >= 2.75 & avg_rating < 3      ~ "2.75 - 3.00",
                                    avg_rating >= 3.00 & avg_rating < 3.25   ~ "3.00 - 3.25",
                                    avg_rating >= 3.25 & avg_rating <= 3.50  ~ "3.25 - 3.50")) %>%
  mutate(label = if_else(is.na(avg_rating_cat), NA_character_, name))

```

#### Palette
```{r}
library(showtext); showtext_auto()
font_add_google("Rock Salt", "rock")
font_add_google("", "")
```

```{r}
library(ggrepel)

plot_base <- 
ggplot(data = cao_world) +
  geom_sf(aes(fill = fill), color = "white", size = 0.15, alpha = 0.6) +
  geom_point(aes(size = n, color = avg_rating_cat, x = x, y = y)) +
  scale_size_continuous(range = c(1, 6)) +
  scale_fill_identity() +
  scale_color_manual(values = c("#C39B77", "#835345", "#693214", "#341c14"), na.translate = FALSE) +
  guides(color = guide_legend(override.aes = list(size = 6))) +
  geom_text_repel(aes(label = label, x = x, y = y)) + 
  labs(color = "Average\nCocoa\nRating",
       size  = "Number of\nChocolate\nBars") +
  coord_sf(crs = vdg_coord) + 
  theme_void() +
  theme(legend.position = c(0.20, 0.40),
        legend.direction = "vertical", 
        legend.box = "horizontal",
        legend.margin = margin(0,-.05,0,-0.05, unit = "cm"),
        legend.title = element_text(face = "bold", family = "rock", hjust = 0))

```

#### Panel
```{r}
library(cowplot)

# finalise panel with layered plotting or annotation
ggdraw() +
  draw_plot(plot_base) +
  draw_text("The Mighty Cocoa Bean", family = "rock", size = 28,
            x = 0.6, y = 0.39) +
  draw_text("Data: FlavorsOfCocoa.com | Graphic: @NearAndDistant", family = "rock", size = 8,
            x = 0.66, y = 0.35)

```

#### Saving
```{r}

ggsave(here::here("chocomap.png"), dpi = 360, height = 10, width = 12, bg = "white")

```

***

R markdown allows to easily format your text. You can add [links](www.r-graph-gallery.com), write in **bold** or *italic*.

Further formatting can be found [here](https://holtzy.github.io/Pimp-my-rmd/)

***