---
title: "Tidy Template"
author: "NearAndDistant"
date: "29/09/2021"
output: html_document
---

## The Historically Black Colleges and Universities (HBCU) Foundaton

***

High school completion and bachelor's degree attainment among persons age 25 and over by race/ethnicity & sex 1910-2016. 

The HBCU article can be found, here: [link](https://theundefeated.com/features/how-hbcus-are-using-more-than-250-million-in-donations/), write in **bold** or *italic*.

Further formatting can be found [here](https://holtzy.github.io/Pimp-my-rmd/)

***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Setup & Import
```{r}
library(tidyverse)

# create driectory for new project
dir.create(here::here("Week 06 : HBCU Foundation"))

# import data for project
hbcu_collage <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-02/hs_students.csv')
hbcu_bachelors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-02/bach_students.csv')

```

#### Clean & Wrangle
```{r}

gather_ethnicity <- 
  function(tbl){
  tbl %>%
    mutate_if(is.character, parse_number) %>%
    rename(year = Total) %>%
    filter(!is.na(year)) %>%
    gather(ethnicity , value , -year) %>%
    mutate(column = if_else(str_detect(ethnicity , "Standard Errors -"), "standard_error", "percent"),
           ethnicity = str_remove(ethnicity , "Standard Errors -")) %>%
    spread(column , value) %>%
    mutate(standard_error = abs(standard_error),
           standard_error = standard_error/100,
           percent = percent/100) %>%
    filter(!is.na(percent)) %>%
    mutate(ethnicity = str_remove(ethnicity , "1$")) %>%
    rename(pc_grad = percent) %>%
    mutate(ethnicity = if_else(str_detect(ethnicity , "- Asian"), "Asian", ethnicity),
           ethnicity = if_else(str_detect(ethnicity , "- Pacific"), "Pacific Islander", ethnicity),
           ethnicity = if_else(str_detect(ethnicity , "American"), "Indigenous", ethnicity)) %>%
    filter(!str_detect(ethnicity , "Total|Two")) %>%
    mutate(pc_non_grad = 1 - pc_grad) %>%
    pivot_longer(cols = c(pc_grad , pc_non_grad), names_to = "graduated") %>%
    mutate(graduated = if_else(graduated == "pc_grad", "% Graduates", "% Non-Graduates"))
  }

```

```{r}

# High School Students
hbcu_collage_cln <-
hbcu_collage %>%
  slice(-c(1:3)) %>%
  gather_ethnicity()

# Bachelors Students
hbcu_bachelors_cln <-
hbcu_bachelors %>%
  gather_ethnicity()

# Join High School and Bachelors
hbcu_edu <-
  bind_rows(hbcu_collage_cln  %>% mutate(degree = "High School"),
            hbcu_bachelors_cln %>% mutate(degree = "Bachlors")) %>%
  mutate(degree = fct_relevel(degree , "High School")) %>%
  select(year , ethnicity , degree , graduated , value)

```

#### Analysis
```{r}
library(scales)
ggplot2::theme_set(theme_minimal())

hbcu_edu %>%
  filter(graduated == "% Graduates") %>%
  ggplot(aes(year , value , color = ethnicity)) +
  geom_line() +
  scale_y_continuous(labels = percent) +
  facet_wrap(~ degree)

```

```{r}
# Holmes Chart - Wide

hbcu_holmes <-
  hbcu_edu %>%
  filter(ethnicity %in% c("White" , "Black")) %>%
  filter(graduated == "% Graduates") %>%
  filter(degree    == "Bachlors") %>%
  mutate(plot_year = strsplit(as.character(year), split = ""),
         n_year    = list(1:4)) %>%
  unnest(c(plot_year , n_year)) %>%
  mutate(y = as.numeric(substr(year,1,3))*10) %>%
  mutate(x = year - y) %>%
  mutate(indicator = as.numeric(substr(as.character(value),3,3))) %>%
  mutate(indicator = if_else(indicator == n_year, "Bold", "Regular"),
         indicator = replace_na(indicator, "Regular"))  %>% # NA indicates less than 10%, won't show up - indicate on graphic
  mutate(y = case_when(year == 1960 ~ 1967,
                       year == 1950 ~ 1965,
                       year == 1940 ~ 1963, TRUE ~ y))

```

```{r}
# Holmes Chart - Long

hbcu_holmes_long <-
  hbcu_edu %>%
  filter(ethnicity %in% c("White" , "Black")) %>%
  filter(graduated == "% Graduates") %>%
  filter(degree    == "Bachlors") %>%
  mutate(plot_year = strsplit(as.character(year), split = ""),
         n_year    = list(1:4)) %>%
  unnest(c(plot_year , n_year)) %>%
  ####
  mutate(y = if_else(as.numeric(substr(year,4,4)) < 5,
                     as.numeric(substr(year,1,3))*10,
                     (as.numeric(substr(year,1,3))*10)+5)) %>%
  mutate(x = if_else(as.numeric(substr(year,4,4)) < 5,
                     year - y,
                     as.numeric(substr(year,4,4))-5)) %>%
  mutate(indicator = as.numeric(substr(as.character(value),3,3))) %>%
  mutate(indicator = if_else(indicator == n_year, "Bold", "Regular"),
         indicator = replace_na(indicator, "Regular"))  %>% # NA indicates less than 10%, won't show up - indicate on graphic
  #mutate(y = if_else(y %in% c(1940 , 1950), 1960, y)) %>%
  mutate(y = case_when(year == 1980 ~ 1981,
                       year == 1975 ~ 1978,
                       year == 1970 ~ 1975,
                       year == 1960 ~ 1972,
                       year == 1950 ~ 1969,
                       year == 1940 ~ 1966, TRUE ~ y)) %>%
  mutate(y = if_else(indicator == "Bold", y - 0.60, y)) 
  
```

```{r}

# Annotations
hbcu_mask <-
hbcu_holmes %>%
  filter(indicator == "Bold") %>%
  mutate(y = y - 0.60) 

```

#### Palette
```{r}
library(showtext); showtext_auto()
font_add_google("Cutive", "cutive")
font_add_google("Patrick Hand" , "patrick")
# BLM Font available, here: https://blacklivesmatterfont.com
font_add("blm", "Black Lives Matter.otf")

font <- "blm"

# Pebble:   "#333333"
# Slate:    "#3E3D53"
# Pewter:   "#696880"
# Fossil:   "#787276"
# Graphite: "#594D5B"
# Stone:    "#59788E"
# Spruce:   "#2C3E4C"
# BLM:      "#424042"
background <- "#2C3E4C"

```

#### Plotting
```{r}
# Holmes Plot

plot_hbcu_long <-
hbcu_holmes_long %>%
anti_join(hbcu_mask , by = c("year" , "n_year")) %>%
ggplot(aes(x = x + (n_year/5), y = -y)) +
  geom_text(aes(label = plot_year), 
            hjust = 0, size = 10, family = font,
            show.legend = FALSE, color = "grey80", alpha = 0.1) +
  geom_text(data = hbcu_mask_long , 
            aes(label = plot_year, color = ethnicity), 
            hjust = 0 , size = 12, family = font, show.legend = FALSE) +
  labs(color = NULL) +
  scale_y_continuous(minor_breaks = NULL) +
  scale_color_manual(values = c(Black = "black" , White = "white")) +
  theme_void()+
  theme(legend.position = c(0.95,0.95),
        panel.background = element_rect(color = background , fill = background , size = 2),
        plot.background  = element_rect(color = background , fill = background),
        plot.margin = margin(0.5,0.5,0,0, unit = "cm"))

```

#### Legend
```{r}

plot_legend <-
hbcu_holmes_long %>%
anti_join(hbcu_mask , by = c("year" , "n_year")) %>%
filter(year == 2001) %>%
ggplot(aes(x = x + (n_year/5), y = -y)) +
  geom_text(aes(label = plot_year), 
            hjust = 0, size = 10, family = font,
            show.legend = FALSE, color = "grey80", alpha = 0.6) +
  geom_text(data = hbcu_mask_long %>% filter(year == 2001) , 
            aes(label = plot_year, color = ethnicity), 
            hjust = 0 , size = 12, family = font, show.legend = FALSE) +
  labs(color = NULL) +
  scale_y_continuous(minor_breaks = NULL) +
  scale_color_manual(values = c(Black = "black" , White = "white")) +
  coord_cartesian(clip = "off") +
  theme_void()+
  theme(legend.position = c(0.95,0.95),
        panel.background = element_blank(),
        plot.background  = element_blank())
```

#### Panel
```{r}
library(cowplot)

text <- 
"This graphic shows the National Centre for Education Statistics' (NCES) data of Bachlor\nlevel graduations of white and black students (over 25) in the United States between 1940 and 2016.\nBlack graduate rates have always lagged behind white rates quite significantly, never reaching parity.\n\nThis inequality is the result of intergenerational capital (both financial and social) as well\nas continued social divides causing an unequal network of opportunities. This continued division,\nunless intervened within, will continue to prevail within the US."

# finalise panel with layered plotting or annotation
panel_blm <-
ggdraw() +
  draw_plot(plot_hbcu_long) +
  annotate(geom = "rect" , xmin = 0.81 , xmax = 0.96 , ymin = 0.82 , ymax = 0.92, fill = colorspace::darken(background, 0.25)) +
  draw_plot(plot_legend , height = 0.02 , width = 0.1315, x = 0.815 , y = 0.86) +
  draw_image("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Fist.svg/842px-Fist.svg.png",
             height = 0.325 , width = 0.25 , x = 0.54 , y = 0.645) +
  draw_text("Educational Inequality\nin the United States", size = 38, x = 0.22 , 0.895 , hjust = 0 , family = "blm") +
  draw_text(text ,  size = 12, x = 0.22 , y = 0.73 , hjust = 0 , family = "patrick") +
  draw_text("Data:\n\nGraphic: " ,  x = 0.71 , y = 0.70 , hjust = 0 , family = "blm" , size = 14) +
  draw_text("NCES via HBCU\n\n@NearAndDistant" ,  x = 0.71 , y = 0.68 , hjust = 0 , family = "patrick" , size = 13) +
  annotate(geom = "curve" , x = 0.90, y = 0.95, xend = 0.8675, yend = 0.90, curvature = 0.5 , arrow = arrow(length = unit(0.01, "npc"))) +
  annotate(geom = "curve" , x = 0.80, y = 0.95, xend = 0.8275, yend = 0.90, curvature = -0.5 , arrow = arrow(length = unit(0.01, "npc"))) +
  draw_text("Black                              White" , x = 0.77, y = 0.95 , hjust = 0 , family = "blm") +
  annotate(geom = "segment" , x = 0.81 , xend = 0.96 , y = 0.80 , yend = 0.80 , arrow = arrow(length = unit(0.01, "npc"), ends = "both")) +
  draw_text("          |         |          |      ", x = 0.81 , y = 0.802, hjust = 0) +
  draw_text("10%     20%     30%      40%     50%", x = 0.81 , y = 0.78, hjust = 0, family = "patrick") +
  draw_text("Percentage of Graduates", x = 0.885 , y = 0.755, hjust = 0.5, family = "blm") +
  draw_text("We represent the % of black and white graduate \nstudents in each particular year by using each\nfigure as % bins (shown above) and highlighting\nwhich each race fell into in each respective year", 
            x = 0.80 , y = 0.695, hjust = 0 , family = "patrick", size = 11)
  
```

#### Saving
```{r}

ggsave(plot = panel_blm , here::here("Week 06 : HBCU Foundation/hbcu_text_chart.png"), dpi = 360, height = 10, width = 16)

```
