---
title: "Tidy Template"
author: "NearAndDistant"
date: "29/09/2021"
output: html_document
---

##  

#### Setup & Import
```{r}
library(tidyverse)

# create driectory for new project
dir.create(here::here("Week 8 : Democracy in Crisis"))

# import data for project
f_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-22/freedom.csv')

```

#### Clean & Wrangle
```{r}

f <-
  f_raw %>%
  janitor::clean_names() %>%
  rename(civil_liberties = cl, political_rights = pr, least_dev = is_ldc) %>%
  mutate(status = case_when(status == "F"  ~ "Free",
                            status == "NF" ~ "Not Free",
                            status == "PF" ~ "Partially Free")) %>%
  mutate(country = case_when(country == "United Kingdom of Great Britain and Northern Ireland" ~ "United Kingdom",
                             country == "Russian Federation"  ~ "Russia",
                             country == "Republic of Moldova" ~ "Moldova",
                             country == "North Macedonia" ~ "Macedonia",
                             TRUE ~ country))

```

#### Palette
```{r}
library(showtext); showtext_auto()
font_add_google("Goudy Bookletter 1911", "1911")
font_add_google("", "")

background <- 
palette    <- 

```

#### Plotting
```{r, fig.align="center", fig.width=6, fig.height=6, fig.cap="Figure: Here is a really important caption."}
ggplot2::theme_set(theme_minimal())

f_eu  <- f %>% filter(region_name == "Europe")
 
ne    <- rnaturalearthdata::countries50 %>% sf::st_as_sf() %>% janitor::clean_names() %>% select(country = geounit)

# join map and data
sf::sf_use_s2(FALSE)
f_ne <- ne %>% right_join(f_eu, by = "country") %>% st_crop(xmin = -25, xmax = 180, ymin = 25, ymax = 90)

# transform to vang
target_crs <- "+proj=vandg +lon_0=0 +x_0=0 +y_0=0 +R_A +a=6371000 +b=6371000 +units=m +no_defs"
f_ne_trans <- st_transform(f_ne, crs = target_crs) 

# plot
library(sf)
library(ggalt)

map_eu <-
f_ne_trans %>%
#filter(year != 1995) %>%
filter(year %in% seq(1998,2020,2)) %>%
mutate(label = if_else(country == "Russia", paste0(year,"\n", status), NA_character_)) %>%
  ggplot() +
  geom_sf(aes(geometry = geometry, fill = political_rights), color = "white", size = 0.2) +
  nord::scale_fill_nord(palette = "halifax_harbor", discrete = FALSE,
                        labels = c("Free", "", "", "Partially Free", "", "", "Not Free")) +
  geom_sf_text(aes(label = label), color = "white", family = "1911") +
  facet_wrap(~year, ncol = 4, strip.position = "bottom") +
  coord_sf() +
  labs(caption = "Data: Freedom House | Graphic: @NearAndDistant",
       fill  = NULL) +
  theme_void() +
  theme(
    plot.caption = element_text(size = 10,  family = "1911", vjust = 0, hjust = 0.5),
    strip.text   = element_blank(),
    legend.position   = c(0.50, 1.03), # 0.1575
    legend.direction  = "horizontal",
    legend.key.width  = unit(2.22, unit = "cm"),
    legend.key.height = unit(0.25, units = "cm"),
    legend.text       = element_text(family = "1911"),
    plot.background   = element_rect(fill = "#a1bbc3", color = "#a1bbc3"),
    panel.background  = element_rect(fill = "#a1bbc3", color = "#a1bbc3"),
    plot.margin = margin(2.75,0,0.5,0, unit = "cm")
  )

```

#### Panel
```{r}
library(cowplot)

# finalise panel with layered plotting or annotation
map_russia <-
ggdraw(map_eu) +
  draw_text("Political Freedom in Russia", size = 30,  family = "1911", vjust = 8, hjust = 0.5,
            x = 0.5, 1.21) +
  draw_text("Constitutional amendments approved in 2020 allow Putin (President since 2000), but not future presidents, to run for an additional two consecutive terms as president, potentially extending his rule to 2036.", family = "1911", size = 10,
            x = 0.5, y = 0.91)

```

#### Saving
```{r}

ggsave(here::here("Week 8 : Democracy in Crisis/russia.png"), dpi = 360, height = 8, width = 15)

```

***

R markdown allows to easily format your text. You can add [links](www.r-graph-gallery.com), write in **bold** or *italic*.

Further formatting can be found [here](https://holtzy.github.io/Pimp-my-rmd/)

***